builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
brews:
- name: goreleaser-testing
  homepage: https://github.com/PatrickMenoti/homebrew-tools 
  tap:
    owner: PatrickMenoti
    name: homebrew-tools

nfpms:
  - id: packages
    license: MIT
    package_name: goreleaser-testing
    maintainer: PatrickMenoti
    homepage: https://github.com/PatrickMenoti/goreleaser-testing
    bindir: /usr/local/bin
    builds:
      - goreleaser-testing
    formats:
      - apk
      - deb
      - rpm

furies:
- account: "{{ .Env.FURY_ACCOUNT }}"

# publishers:
#   - name: fury.io
#     # by specifying `packages` id here goreleaser will only use this publisher
#     # with artifacts identified by this id
#     ids:
#       - packages
#     dir: "{{ dir .ArtifactPath }}"
#     cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/netdevops/

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
