builds:
  - env:
      - CGO_ENABLED=0
    binary: azioncli
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
brews:
- name: goreleaser-testing
  homepage: https://github.com/PatrickMenoti/homebrew-tools 
  tap:
    owner: PatrickMenoti
    name: homebrew-tools

nfpms:
  - id: packages
    license: MIT
    package_name: goreleaser-testing
    maintainer: PatrickMenoti
    homepage: https://github.com/PatrickMenoti/goreleaser-testing
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm

# furies:
# - account: "{{ .Env.FURY_ACCOUNT }}"

publishers:
  - name: fury.io
    # by specifying `packages` id here goreleaser will only use this publisher
    # with artifacts identified by this id
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/patrickmenoti/

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.BIN_VERSION }}_{{ .Env.BIN_VERSION }}"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
