builds:
  - env:
      - CGO_ENABLED=0
    binary: azioncli
    id: "azioncli"
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
  - files:
    - README.md
    - LICENSE.md
    - completions/*

before:
  hooks:
    - ./scripts/completions.sh
      
brews:
  - name: goreleaser-testing
    homepage: https://github.com/PatrickMenoti/homebrew-tools
    tap:
      owner: PatrickMenoti
      name: homebrew-tools
    install: |
      bin.install "azioncli"
      bash_completion.install "completions/azioncli.bash" => "azioncli"
      zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
      fish_completion.install "completions/azioncli.fish" 

nfpms:
  - id: packages
    license: MIT
    package_name: goreleaser-testing
    maintainer: PatrickMenoti
    homepage: https://github.com/PatrickMenoti/goreleaser-testing
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
  - contents:
    - src: ./completions/azioncli.bash
      dst: /usr/share/bash-completion/completions/azioncli
      file_info:
        mode: 0644
    - src: ./completions/azioncli.fish
      dst: /usr/share/fish/vendor_completions.d/azioncli.fish
      file_info:
        mode: 0644
    - src: ./completions/azioncli.zsh
      dst: /usr/share/zsh/vendor-completions/_azioncli
      file_info:
        mode: 0644

# furies:
# - account: "{{ .Env.FURY_ACCOUNT }}"

publishers:
  - name: fury.io
    # by specifying `packages` id here goreleaser will only use this publisher
    # with artifacts identified by this id
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/patrickmenoti/

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.BIN_VERSION }}_{{ .Env.BIN_VERSION }}"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

aurs:
  - package: |
      # bin
      install -Dm755 "./azioncli" "${pkgdir}/usr/bin/azioncli"
      # license
      install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/azioncli/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/azioncli.bash" "${pkgdir}/usr/share/bash-completion/completions/azioncli"
      install -Dm644 "./completions/azioncli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_azioncli"
      install -Dm644 "./completions/azioncli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/azioncli.fish"